### ISSUE TITLE
dart error !

### ISSUE THREAD

**Issue by biancashouse** [bsutton/critical_test#6]
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/dcli-2.2.0/lib/src/util/wait_for_ex.dart:38:17: Error: Method not found: 'waitFor'.
    value = cli.waitFor<T>(wrapped);
                ^^^^^^^

**Comment by biancashouse** [comment]
BTW - on Windows 10, Android Studio JellyFish

**Comment by bsutton** [comment]
What version is critical test are you running?

**Comment by bsutton** [comment]
OK, I thought I had updated critical test with the lastest version of dcli. 
It turns out I hadn't 

I've just released ct 8.0 with a fix.
